### PR TITLE
feat(dependencies): add image for dotnet core

### PR DESCRIPTION
**Pull request by tfenster**

### CODE REVIEW

**Comment by lippertmarkus** [comment]
changing the BC build agent image also needs changes the docker automation cleanup and also in the pipeline (?)

**Comment by tfenster** [comment]
> changing the BC build agent image name also requires changes in the docker automation cleanup and also in the pipeline (?)

I didn't intend to do a rollout for the bcagent image, would only do that on a new version. Am I missing anythin?

**Comment by lippertmarkus** [comment]
no, we just shouldn't forget it to change it everywhere for the next rollout

**Review by lippertmarkus — APPROVED** [review]

**Comment by tfenster** [comment]
> no, we just shouldn't forget it to change it everywhere for the next rollout

I thought we would definitely remember when we increase the version, but now you've probably jinxed it ;)

**Pull request merged**
